### ISSUE TITLE
How to create a project with Code Composer Studio on Ubuntu

### ISSUE THREAD

**Issue by NicolasGoeddel** [yuvadm/tiva-c#2]
Hi,

these are my first steps with the Tiva™ C Series Connected Launchpad (EK-TM4C1294XL) and ARM generally. I can build the blinky example and flash it to the board and it works great. But I had problems to create a new project in CCS with the GNU Toolchain and your library as include. I think CCS does no create the makefile correctly. If I use your Makefile and modify it it works, but it is difficult to find the right files for the linker and so on. Is there a How To for creating a new project in a workspace different from the examples folder of your library and automatically creating a correct Makefile? And how can I use the debugger?

**Comment by yuvadm** [comment]
Good questions, but they are out of scope for this project, and I've never personally used CCS so it's hard for me to help there.
